// <auto-generated />
namespace Homework05.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class X_Coordinator_Group : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(X_Coordinator_Group));
        
        string IMigrationMetadata.Id
        {
            get { return "201712132332498_X_Coordinator_Group"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
